# Generated by Django 5.1.2 on 2025-03-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='subdomain_name',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='stores.storetheme'),
        ),
    ]
