# Generated by Django 5.1.2 on 2025-03-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='description',
        ),
    ]
